### ISSUE TITLE
Always show NaN in iteration progress

### ISSUE THREAD

**Issue by archenal** [oxfordcontrol/CDCS#14]
Hi,

Thanks for your work.

I am trying to check the feasibility of some LMIs. During the iteration progress of CDCS, all the elements show as NaN. One instance is attached (Matlab code, but save as txt to upload).
[Code_for_Seuret2013AutomaticaCase3.txt](https://github.com/oxfordcontrol/CDCS/files/4358795/Code_for_Seuret2013AutomaticaCase3.txt)

I also tried to check the feasibilities of some simple Lyapunov inequalities, and they were successfully solved. 

My question is: can the instance be solved by CDCS? If so, how to fix my code.

Thanks

**Comment by giofantuzzi** [comment]
Hi @archenal ,

First of all, thanks for reporting the issue and for your interest in CDCS.

It seems like there is a problem with the `hsde` module in CDCS. However, the `primal` and `dual` modules seem to work fine.  Precisely, with the following options the problem was solved successfully:

**Case 1**: no chordal decomposition, `dual` method
````
ops.cdcs.chordalize = 0;
ops.cdcs.solver = 'dual';
````
**Case 2**: no chordal decomposition, `primal` method
````
ops.cdcs.chordalize = 0;
ops.cdcs.solver = 'primal';
````
**Case 3**: with chordal decomposition, `dual` method
````
ops.cdcs.chordalize = 1;
ops.cdcs.solver = 'dual';
````
**Case 4**: with chordal decomposition, `primal` method
````
ops.cdcs.chordalize = 1;
ops.cdcs.solver = 'primal;
````

Please let @zhengy09 or myself check if there is a bug in the `hsde` module. Meanwhile, I recommend that you use the options above.

Finally, note that CDCS has been designed to tackle large-scale semidefinite programs with sparse LMIs. If all of your problems are as small as this example and your LMIs are not sparse, then you may wish to consider a different solver.

**Comment by archenal** [comment]
Hi Giovanni,

Thanks for your quick reply!

Your solutions work well. It is really helpful. I do have large-scale sparse SDPs to solve, and this toy example is just for reporting the problem.
