### ISSUE TITLE
[Question] flatten function input arguments

### ISSUE THREAD

**Issue by alexmaraval** [oxfordcontrol/CDCS#15]
Hi, I have a question regarding the function flatten in `CDCS/packages/+cdcs_utils/flatten.m`.

I think I understand what it is supposed to do; namely take a cell array containing arrays of various sizes, flatten each one of them and stack them up in a big column.

The part that I am confused about is the inputs of this function. 

The function takes in 3 different aguments, lower case `z`, upper case `Z` and a flag `svecFlag` that is used to call `CDCS/packages/+cdcs_utils/private/svec.c`.
However, I don't see the first argument (lower case `z`) being used anywhere.

The last line of the function creates a lower case `z` that is the returned object but as far as I understand this is not per say using the `z` passed as input.

Is there something I am missing ?
Thanks a lot for any feedback :)

**Comment by Jarmill** [comment]
The first argument of 'flatten' does appear unnecessary. It appears that only the second argument is used.

It should be sufficient to change flatten to a 2-argument function:

`flatten(Z, svecFlag)`

where svecFlag = 1 by default.

I think @zhengy09 will need to comment on this.

In CDCS\packages\+cdcs_utils\updateU.m, line 11 is:

`u.x = cdcs_utils.flatten(v.x,X);`

v.X and X are different, but i'm not sure what should be assigned to u.x.

Thanks for pointing this out.

-Jared

**Comment by giofantuzzi** [comment]
Hi @alexmaraval and @Jarmill,

Thanks for your query. The input `z` is passed in so MATLAB (depending on the particular version used) can (hopefully) perform in-place operations, rather than creating a new instance of the variable. This should avoid the allocation of new memory and slightly speed up the function.

I think @zhengy09  will be able to confirm.

Hope this helps,
Gio

**Comment by Jarmill** [comment]
Guess the answer is implementation tricks.

Classic matlab.

**Comment by giofantuzzi** [comment]
> Guess the answer is implementation tricks.

Correct. MATLAB is good for quick prototyping but finer details are a little harder to control.

**Comment by alexmaraval** [comment]
Hi @giofantuzzi, thanks for the super quick reply !

I thought it could be similar to passing by reference to change the first argument passed _in place_ as you mentioned. I tried it on my Matlab version and it did not do that so maybe I need to check my own version.

But if that is the idea, can you clarify what is intended in this code for instance ?
```
% Import functions
import cdcs_utils.flatten

% Extract some variables
Ex = flatten(Y.vec,X.blk);
y = Y.vec;
```
These are lines 18-23 of `CDCS/packages/+cdcs_pd/private/checkConvergence.m`.
In the code above, is the intention to flatten `X.blk` (let us call it `X_blk_flat`) and to change `Y.vec` _in place_ with `X.blk_flat` ?
If that is the case, then would `Ex` also contain the `X_blk_flat` as so would `y` ?

I must be missing something in the `flatten()` function because if its goal is changing _in place_ the first argument with the flattened second, why bother returning the very same vector the first argument now points to ?

My apologies if this is trivial but it seems to make a possible difference in implementation across different Matlab versions.

thanks for the help :)
Alex

**Comment by giofantuzzi** [comment]
Hi @alexmaraval,

>In the code above, is the intention to flatten X.blk (let us call it X_blk_flat) and to change Y.vec in place with X.blk_flat ?
If that is the case, then would Ex also contain the X_blk_flat as so would y ?

Here Ex and y will contain different values, but they should agree when the algorithm has converged. We do not want to modify Y.vec here, and it does not happen because the output and input names differ (I think). I agree that this way of using the function is confusing and a better code would probably be:

```
% a vector Ex passed as input
y = Y.vec;    % extract y (for convenience -- we should really use Y.vec instead of making a copy)
Ex = flatten([], X.blk) % flatten X.blk into a new variable Ex (no in-place assignment)
```

Once again, @zhengy09 may be able to confirm.

Finally, let me point out that you are very likely find many more such inconsistencies in the code (but hopefully they should not cause any bugs!). CDCS was meant primarily as a proof of concept for our structure-exploiting algorithms, rather than a super-efficient and extremely robust solver. Had that been the aim, we wouldn't have coded it up in MATLAB :-)

**Comment by alexmaraval** [comment]
@giofantuzzi Ok I think I get it now ! many thanks for taking the time to explain :)
