### ISSUE TITLE
Result contains NaN when CDCS stops after maxIter

### ISSUE THREAD

**Issue by martinandersen** [oxfordcontrol/CDCS#5]
CDCS stops after maxIter iterations and returns a vector X that contains NaNs when I try to solve the following problem instance: [prob.zip](https://github.com/oxfordcontrol/CDCS/files/1155629/prob.zip)

I observe the same problem with many other problem instances. Could this be a problem with my installation or a bug in CDCS? I'm using the most recent version of CDCS from this repo with MATLAB R2017a on macOS.

```
clear all
load prob.mat
[x,y,sedumi_info] = sedumi(A,b,c,K);

opts = cdcsOpts;
opts.maxIter = 5000;
[xt,yt,zt,cdcs_info] = cdcs(A,b,c,K,opts);

any(isnan(xt))
```

**Comment by giofantuzzi** [comment]
Dear Martin,

thanks for raising this issue. There is nothing wrong with your installation: the vector `xt` contains `NaN`'s if CDCS reaches the maximum number of iterations (this is your case) or encounters a problem in the matrix completion step just before returning the optimal solution.  In the first case, it makes no  sense to attempt to complete the vector `xt`, because if `xt` is not a solution this completion will most likely not exist. In the second case, the problem arises in a subroutine which we borrow from [SparseCoLO](http://www.is.titech.ac.jp/~kojima/SparseCoLO/SparseCoLO.htm) and is due to the fact that CDCS only gives a solution of moderate accuracy.  Basically, it may not be possible to find a positive semidefinite completion when the "optimal" vector `xt` is not sufficiently accurate. Tightening the tolerances for your particular problem resolves the issue on our machines:

```
clear
load prob.mat

opts = cdcsOpts;
opts.relTol = 1e-6;                                    % tight stopping criterion
opts.maxIter = 1e4;                                    % increase iterations to prevent premature stop
opts.rescale = 0;                                      % this seems to work better on this particular SDP
[xt,yt,zt,cdcs_info] = cdcs(A,b,c,K,opts);

any(isnan(xt))
```

In the short term we will make CDCS issue a warning for `NaN`'s when the matrix completion is unsuccessful, and we will look into improving the completion step in the future.

I hope this helps, but please do let us know if you have any other questions.

Best,
Giovanni

**Comment by martinandersen** [comment]
OK, thanks for clarifying this.
